Polishing up for release

diff --git a/fabric/bin/stork-fabric-deploy b/fabric/bin/stork-fabric-deploy
--- a/fabric/bin/stork-fabric-deploy
+++ b/fabric/bin/stork-fabric-deploy
@@ -20,16 +20,16 @@ cd "$INITIAL_WORKING_DIR"
 
 buildTaskArgs()
 {
-   local args=$1
-   local arg_name=$2
-   local arg_val=$3
+    local args=$1
+    local arg_name=$2
+    local arg_val=$3
 
-   if [ -z "$args" ]; then
-     echo ":$arg_name=$arg_val"
-   else
-     echo "$args,$arg_name=$arg_val"
-   fi
-   echo
+    if [ -z "$args" ]; then
+        echo ":$arg_name=$arg_val"
+    else
+        echo "$args,$arg_name=$arg_val"
+    fi
+    echo
 }
 
 # process arguments -- strip out ones that go to deploy task
@@ -38,26 +38,34 @@ ASSEMBLY=""
 FABRIC_ARGS=""
 while [ $# -gt 0 ]; do
     a=$1
-	if [ "$a" = "--assembly" ]; then
-		shift
-		if [ $# -le 0 ]; then continue; fi
-		ASSEMBLY=$1
-	else
+    if [ "$a" = "--assembly" ]; then
+        shift
+        if [ $# -le 0 ]; then
+            continue;
+        fi
+        ASSEMBLY=$1
+    else
     	# does the argument need escaped?
     	if [ "$a" = `echo "$a" | sed 's/ //g'` ]; then
-        	FABRIC_ARGS="$FABRIC_ARGS $a"
+            FABRIC_ARGS="$FABRIC_ARGS $a"
     	else
-        	FABRIC_ARGS="$FABRIC_ARGS \"$a\""
+            FABRIC_ARGS="$FABRIC_ARGS \"$a\""
     	fi
-	fi
+    fi
     shift
 done
 
 # build command line for deploy task
 TASK_ARGS=""
 if [ ! -z "$ASSEMBLY" ]; then
-  TASK_ARGS=`buildTaskArgs "$TASK_ARGS" "assembly" "$ASSEMBLY"`
+    TASK_ARGS=`buildTaskArgs "$TASK_ARGS" "assembly" "$ASSEMBLY"`
+else
+    echo "Error: --assembly parameter missing"
+    echo "Usage: stork-fabric-deploy --assembly <tarball> [any other fabric params]"
+    echo "Example:"
+    echo "stork-fabric-deploy --assembly app-1.0.tar.gz -H host.example.com"
+    exit 1
 fi
 
 # fab -H sea-web2.fizzed.lan deploy:assembly=../examples/hello-server-dropwizard/target/hello-server-dropwizard-1.0.0-SNAPSHOT.tar.gz
-PYTHONDONTWRITEBYTECODE=1 fab --fabfile="$APP_HOME/fabfile.py" $FABRIC_ARGS deploy"$TASK_ARGS"
+PYTHONDONTWRITEBYTECODE=1 fab --fabfile="$APP_HOME/storkfab.py" $FABRIC_ARGS deploy"$TASK_ARGS"
